---
- name: Install and uninstall Visual Studio Code
  hosts: localhost
  vars:
    ## User name
    USER: u987891158
    
    ## Visual Studio Code extension list
    VSC_EXT_LIST:
    - ms-azuretools.vscode-docker
    - ms-vscode-remote.remote-containers

  tasks:
    - name: Add repository into repo.d list (1/3)
      ansible.builtin.yum_repository:
        name: code
        description: Visual Studio Code repository
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        enabled: true
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      tags: install

    - name: Installing the Visual Studio Code package (2/3)
      ansible.builtin.package:
        name: code
        state: latest
        update_cache: true
      tags: install

    - name: Uninstall the VSC package (1/3)
      ansible.builtin.package:
        name: code
        state: absent
      tags: uninstall

    - name: Remove .vscode directory (2/3)
      become_user: "{{ USER }}"
      ansible.builtin.shell: /bin/rm -rf /home/{{ USER }}/.vscode
      tags: uninstall

    - name: Remove code.repo from the repository list (3/3)
      ansible.builtin.shell: /bin/rm -f /etc/yum.repos.d/code.repo
      become: true
      tags: uninstall

    - name: Install a list of extension (3/3)
      shell: code --install-extension {{ item }}
      become: true
      become_user: "{{ USER }}"
      with_items: "{{ VSC_EXT_LIST }}"
      tags: install

